### ISSUE TITLE
System.FormatException

### ISSUE THREAD

**Issue by Nighthound242** [Wiedmolol/CQMacroCreator#10]
Hi there,

since the latest update the MacroCreator has stopped working for me. It says in the ExceptionLog :

System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   bei CQMacroCreator.Form1.init()
   bei CQMacroCreator.Form1..ctor()
   bei CQMacroCreator.Program.Main()

This is Probably due to my German System. Any Idea how to fix this?

Thank you

PS: Keep up the good work. I really appreciate it!

**Comment by Wiedmolol** [comment]
I need to know what your default follower settings are. In Settings.json(you can open it with any text editor) you can see it under "defaultLowerLimit" and "defaultUpperLimit". Supported formats are "x" and "x%" where x is a whole number without spaces so "10000" will work, "-1" will work, "10%" will work but 
"15 000"or "33.3%" will fail.

**Comment by Nighthound242** [comment]
2000000 and 100% worked fine with the other versions.

Edit:
I just now tried it without the MacroSettings.txt (renamed it) and got the same error.

Edit 2:
Ok, don't ask me why but I tried it on my second Maschine (Win7) and it worked fine, I then copied all files to the other, overwrote everything and now it works there too. Beats me what the difference was.

You can consider the issue closed. Thanks for your help!
