### ISSUE TITLE
Macro Setting Lower Limit bug?

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQMacroCreator#3]
Ok, so, normally I had the lower limit in the Macro Setting file to 200,000 but have started moving it to 30% in the Other screen when/if I crash due to memory.
So, got tired of it finally and set 30% in the Macro Setting file, started the prog up, and it didn't have any heroes selected. I went back to 200K and it had 8 heroes when I restarted.
I played around with some different %'s and like at 20% it selected 6.
Now, the more interesting thing is that with 30%, even if I CLICK "Select best heroes" nothing will be selected at all. If I select Check/Uncheck then Select, it will SAY there are 5 selected heroes, but there won't actually be any selected.
Also, I tested this by actually entering the 30% value into the Macro Settings file, and got the exact same results I gave above.
But, when I select 30% in the program itself, there is no issues.
I'd provide a screenshot as proof, but since the window isn't maximizable all you see is part of the screen, and I don't think it's actual proof when some checkboxes are hidden because I could be BS'ing and making this up.
Am I the only one that runs into this?
Guessing for now, I'll have to keep doing it the way I am and just start it up with 200000 and click 30%

EDIT: Ok, so, just reset to 200000, clicked Check/Uncheck and then Select best heroes, and for some reason, the same issue happened. It said 5 heroes selected, but none actually are.
Honestly, don't recall that being an issue before. Pretty sure I'd gone to 30% and then checked all and then best when going between DQ's and Quests.
No idea at this point what's up.

FWIT: I'm on Windows 7 - 64Bit. Totally updated.

**Comment by Wiedmolol** [comment]
I'll just copy paste what I wrote on kong forums: 

> Best heroes option was changed and it ignores heroes that have strength lower than your current lower follower limit. That means that if your lower limit is set to e.g. 400k it will ignore all commons(even maxed) and low level rares and legs. If the lower limit is even higher than it will also ignore maxed rares etc. Other than that I haven't found any reasons why you would say it doesn't work.

I'll check if it selects heroes properly though cause if you say that app claims that 5 heroes are selected while none of them actually are then it might be a bug.

**Comment by saynotoid** [comment]
im not watching kong forum, so big thx for sharing this - it would be awesome to have it listed in patch-notes some documentation here on github though as the last WHAT's new is 'v. 2.9.1 - added quest support. GUI can now send quest solutions to server.'
edit: i mean the readme file or whatever.

**Comment by Vitae666** [comment]
Understandable, but not much help when you want to do the calc for a boss when Heroes are allowed and you have heroes that can do better than the minions and enabling All Heroes crashes the Calc :)

**Comment by Vitae666** [comment]
Ok, so, maybe I'm confused still.
I ran my DQ 59: E17,A15,E15,F15,A15
With 200000 in the Macro Settings file, it loaded with 8 heroes and then I'd clicked in to set it to the 30% lower limit and got this:

Enter Hero 1: atzar:20
Enter Hero 2: nicte:99
Enter Hero 3: forestdruid:99
Enter Hero 4: ignitor:99
Enter Hero 5: chroma:99
Enter Hero 6: petry:99
Enter Hero 7: zaytus:99
Enter Hero 8: ladyodelith:99
Enter Hero 9: done
Set a lower follower limit on monsters used: 2620914
Set an upper follower limit that you want to use: 8736380
Enter Enemy Lineup(s): e17,a15,e15,f15,a15

Calculating with 10 available Monsters and 8 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4

Could not find a solution yet!
Continue calculation? (y/n): y

Preparing to work on loop for armies of size 5
Currently considering 0 normal and 24656 hero armies.
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 5
  Simulating 0 non-hero Fights...                           Done! (  0 seconds)
  Simulating 57843 hero Fights...                           Done! (  0 seconds)
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 6
  Simulating 0 non-hero Fights...                           Done! (  0 seconds)
  Simulating 46762 hero Fights...
    [Followers: 8448000 | a13 ladyodelith:99 zaytus:99 atzar:20 petry:99 f15 <==]
    [Followers: 5676000 | forestdruid:99 ladyodelith:99 zaytus:99 atzar:20 petry:99 f15 <==]
                                                            Done! (  0 seconds)

Solution for [Followers: 47174000 | a15 f15 e15 a15 e17 <==]:
###      **[Followers: 5676000 | forestdruid:99 ladyodelith:99 zaytus:99 atzar:20 petry:99 f15 <==]**

Then said to myself, Ok, so, what will this say is the best set up if I rerun this with the 30% in the Macro Setting file so that it doesn't select any "best heroes"
Maybe it would use less minions?

Enter Hero 1: done
Set a lower follower limit on monsters used: 2620914
Set an upper follower limit that you want to use: 8736380
Enter Enemy Lineup(s): e17,a15,e15,f15,a15

Calculating with 10 available Monsters and 0 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4

Could not find a solution yet!
Continue calculation? (y/n): y

Preparing to work on loop for armies of size 5
Currently considering 0 normal and 0 hero armies.
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 5
  Simulating 0 non-hero Fights...                           Done! (  0 seconds)
  Simulating 0 hero Fights...                               Done! (  0 seconds)
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 6
  Simulating 0 non-hero Fights...                           Done! (  0 seconds)
  Simulating 0 hero Fights...                               Done! (  0 seconds)

Solution for [Followers: 47174000 | a15 f15 e15 a15 e17 <==]:
###    **Could not find a solution that beats this lineup.**

Well, nope, it says that there's no way that I can kill DQ59 without heroes.
So, I'm really not sure how having the automater _"ignore all commons(even maxed) and low level rares and legs."_ helps when doing so will, potentially, result in not having a usable answer.

Am I not understanding something that I should do to get this to work with a proper % in the Macro Setting file that will allow heroes to be used rather than ignored so that passing DQ's happens correctly?
Like I said before, looks like the better option, at least for me, is really to just have a 200K lower limit setting and then change it in the program.

**Comment by Wiedmolol** [comment]
I've uploaded new version with less strict conditions for choosing heroes. Now they will be ignored if their strength is lower than 33% of lower limit instead of 100%. That should fix the problem.
