### ISSUE TITLE
Select best heroes does not work

### ISSUE THREAD

**Issue by Koamh** [Wiedmolol/CQMacroCreator#4]
Hi !

First of all, thanks for your work, it is really great !
I downloaded the new exe file, but now, the button "select best heroes" does not do anything by his own, I must select all the heroes then press the "select best heroes" to have a bunch of heroes selected.

version :2.9.8
OS: windows 10 x64

**Comment by saynotoid** [comment]
try changing the followers limit, or put exact values here for debuggin pls

**Comment by Koamh** [comment]
Ah ok. I didn't noticed that changing the follower limit will have an impact on selecting the best heroes. Is it documented somewhere? 

This issue can be considered as closed. 

Thanks for the very fast answer !
