### ISSUE TITLE
Searching for worse solution

### ISSUE THREAD

**Issue by StanKoko** [Wiedmolol/CQMacroCreator#6]
Last time my MacroCreator crash more often during DQ. I ran some of them manually without sending to server and the example is below. The code found solution but is still runing and searching for worse. At the end the computer is not able to calculate it and finnaly it crash. Why it works like this?

![cosmoq2](https://user-images.githubusercontent.com/38471226/38883934-8f741da8-426e-11e8-96e0-21a69eab3f5f.png)

**Comment by Wiedmolol** [comment]
Cause you are not using lower follower limit so the calc has too many possible lineups to check and you are probably running out of RAM. Set your lower follower limit to at least 500k or something like that. I'm gonna add a warning to macro creator that pops up if you are using to many monsters.

**Comment by Vitae666** [comment]
Don't understand why people ask questions about a program developed by someone else as if it's Wiedmolol/Latas' fault. And it's almost always the same question.
Ask on Dice's version, or any one of the forks for it.
