### ISSUE TITLE
3.0.1d crashes.

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQMacroCreator#8]
Doesn't startup, just crashes right off the bat.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	CQMacroCreator.exe
  Problem Signature 02:	3.0.1.0
  Problem Signature 03:	5afd7a0f
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.2563.0
  Problem Signature 06:	5a334d03
  Problem Signature 07:	334
  Problem Signature 08:	2e
  Problem Signature 09:	System.ArgumentOutOfRange
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0b75
  Additional Information 2:	0b75568a0e6063f8cf7482f4e14934ab
  Additional Information 3:	c0ea
  Additional Information 4:	c0ea3fb5f3ebb5e9eecf94b5491c3827

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

**Comment by Wiedmolol** [comment]
I've already fixed it in 3.0.1e
